# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: "troylindsay.io"
name: "Troy Lindsay"
# email:
description: "about virtualization, automation, and cloud computing"

url: "https://www.troylindsay.io"
baseurl: "" # the subpath of your site, e.g. /blog

github: "[metadata]"
repository: "troylindsay/troylindsay.github.io"

# head_scripts:
#   - https://code.jquery.com/jquery-3.2.1.min.js
#   - /assets/js/your-custom-head-script.js

# teaser: /assets/images/500x300.png

breadcrumbs: true

analytics:
  provider: "google"
  google:
    tracking_id: "UA-117909744-1"

bing_site_verification: "D61B6DA4780B196D884D0F4094F52CE3"
naver_site_verification: "df634f43d5abd10bd587bf3814db1f024bfa5211"
yandex_site_verification: "ebcfad05a879c1e8"

defaults:
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      author_profile: true
      comments: true
      layout: "single"
      share: true
      toc: true
      toc_label: "On this page"
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      author_profile: true
      comments: true
      layout: "single"
      read_time: true
      related: true
      share: true
      toc: true
      toc_label: "On this page"

search: true

# Build settings
markdown: "kramdown"

kramdown:
  input: GFM

#theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum" "sunrise"

timezone: "America/Chicago"

plugins:
  - "jekyll-archives"
  - "jekyll-data"
  - "jekyll-feed"
  - "jekyll-paginate"
  - "jekyll-remote-theme"
  - "jekyll-seo-tag"
  - "jekyll-sitemap"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

paginate: 5 # amount of posts to show
paginate_path: /page:num/

author:
  avatar: "/assets/images/bio-photo.jpg"
  name: "Troy Lindsay"
  bio: "Husband, father of three beautiful children, and passionate architect of cloud solutions."
  location: "Richardson, TX, USA"
  home: "https://www.troylindsay.io/about/"
  uri: "https://www.troylindsay.io"
  twitter: "troylindsay42"
  linkedin: "troylindsay"
  github: "tlindsay42"

github_username: "tlindsay42"
twitter:
  username: "troylindsay42"

comments:
  provider: "disqus"
  disqus:
    shortname: "troylindsay-github-io"
